[Standard of comparison in comparative constructions]{.c6 .c16} {#h.dekv531fwswr .c28 .c14 .c29}
===============================================================

[]{.c4}

[1. Standard of comparison]{.c13 .c6} {#h.2edjm7hzlfjz .c0 .c14}
-------------------------------------

[]{.c4}

Comparative constructions typically involve three elements: a predicate
and two noun phrases denoting the object of comparison and the [standard
of comparison]{.c6}. In example (1) the object of comparison is
constituted by the first noun phrase ([the tree]{.c2}), while the second
noun phrase ([the house]{.c2}) is the standard of comparison (the
preposition [than]{.c2}[ is the standard marker). ]{.c4}

[]{.c4}

\(1)         [The tree is higher]{.c2}[ ]{.c2}[than the house]{.c2
.c6}[.]{.c4}

[]{.c4}

This chapter focuses on the morphological coding of the standard of
comparison in comparative constructions. In the languages of Daghestan,
the comparative meaning of a construction does not involve inflecting
the adjective by degree (i.e. there is no morphological comparative
degree), but the standard of comparison in such constructions is
expressed by a [spatial form]{.c6}, i.e. an inflected form of a nominal
normally expressing a spatial relation. This is one of the most common
strategies used to mark the standard of comparison in the languages of
the world (see
[[https://wals.info/feature/121A\#4/41.57/33.00](https://www.google.com/url?q=https://wals.info/feature/121A%234/41.57/33.00&sa=D&ust=1589986799804000){.c20}]{.c26}).[ ]{.c4}

Cross-linguistically, other common strategies involve the use of
particles (other than those expressing spatial relations)[, predicates
meaning 'exceed, surpass', and conjoined comparatives (see Stassen
2013). Sometimes more than one strategy is available in one and the same
language. In the languages of Daghestan, for instance, constructions
with postpositions are also found. ]{.c4}

Depending on the nature of the marker employed, spatially coded
comparatives can be divided into three types: [At]{.c2}-comparatives
(i.e. essives), [To]{.c2}-comparatives (i.e. latives), and
[From]{.c2}-comparatives (i.e. elatives)[ (cf. Stassen 2013). ]{.c4}

This variation within the group of spatially coded comparatives, which
was not considered for the purposes of the WALS map of comparative
constructions, is the focus of the present investigation. Our goal is to
classify the languages of Daghestan according to the [type of spatial
form used to mark the standard of comparison]{.c6}.

[]{.c4}

[2]{.c3}[. Spatial case systems in the languages of Daghestan]{.c3}^[\[a\]](#cmnt1){#cmnt_ref1}^ {#h.hde9g5ozjgx .c0 .c14}
------------------------------------------------------------------------------------------------

[]{.c4 .c3}

[Most Daghestanian languages feature bimorphemic]{.c3}[ ]{.c3}[spatial
case systems including: ]{.c4 .c3}

[]{.c4 .c3}

1.  [the common distinction between location (essive), destination
    ]{.c3}[(lative)]{.c3}[, source (elative), and path
    (translativ]{.c3}[e)]{.c3}[;]{.c3}[ ]{.c4 .c3}
2.  [a specification of the configuration of an object in space (i.e.
    ]{.c3}[in]{.c2 .c3}[ a container, ]{.c3}[on]{.c2 .c3}[ a surface,
    ]{.c3}[behind]{.c2 .c3}[ another object, etc.). Markers conveying
    such meanings are often called]{.c3}[ ]{.c3}[localization
    markers]{.c3 .c6}[ (cf.]{.c3}[ Daniel & Ganenkov 2009: 674). ]{.c4
    .c3}

[]{.c4 .c3}

[The Godoberi (Avar-Andic) examples in (2) and (3) demonstrate how
spatial forms are constructed.]{.c4 .c3}

[]{.c4 .c3}

[(2)         Godoberi (Saidova 1973: 70)]{.c4 .c3}

[den         ]{.c2 .c3}[bel-qi]{.c2 .c3
.c6}[                 w-un-i-sːu]{.c2 .c3 .c12}

[1sg         ]{.c3}[mountain-ad]{.c3 .c6}[         m-go-is-fut.def]{.c4
.c3}

['I will go to the mountains.']{.c4 .c3}

[]{.c4 .c3}

[(3)         Godoberi (Saidova 1973: 70)]{.c4 .c3}

[riχu-ƛi                 reqi-me         ]{.c2 .c3}[bel-qi-ru]{.c2 .c3
.c6}[                 ]{.c4 .c3}

[        sheep-gen         herd-pl         ]{.c3}[mountain-ad-el]{.c3
.c6}[ ]{.c4 .c3}

[hiƛ'i                 r-a-aƛa-da]{.c12 .c2 .c3}

[down                 nhum.pl-come-prog.cvb-cop]{.c4 .c3}

['The herds are coming down from the mountains.']{.c4 .c3}

[]{.c4}

[3. The standard of comparison in the languages of Daghestan]{.c13 .c6} {#h.ya388aujaxdk .c0 .c14}
-----------------------------------------------------------------------

[]{.c4}

[In the languages of Daghestan the standard of comparison is usually
marked with a spatial form (3.1). There are cases, though less frequent,
of languages featuring a specialized comparative marker (3.2).]{.c4}

[]{.c4}

### [3.1. Spatial forms]{.c12 .c2} {#h.cr8gsznaiua8 .c0 .c14}

[]{.c4}

In comparative constructions, most languages of Daghestan mark the
standard of comparison with a spatial form. In different languages,
variation is observed not only with respect to the choice of a specific
directionality marker (i.e. essive/lative/elative/translative), but also
in terms of the localization marker employed, cf. examples (4) and (5),
contrasting Standard Avar and Tindi (Avar-Andic), in which [superelative
]{.c6}and [contessive ]{.c6}[are used respectively.]{.c4}

[]{.c4}

\(4)         Standard Avar [(Bokarev 1949: 165)]{.c11}

[di-da-sa]{.c2 .c11 .c6}[         ɬik'-a-w         ]{.c2
.c11}[qazaq]{.c2 .c11}[ ]{.c11}

[1sg-sup-el]{.c11 .c6}[         good-adjz-m         worker ]{.c4 .c11}

[du-je=gi         š]{.c2 .c11}[ː]{.c2}[ʷ-ela-r=in]{.c12 .c2 .c11}

[2sg-dat=add         get-fut-neg=emph]{.c4 .c11}

['You will also not get a better farm worker than me.' ]{.c11}

[]{.c4}

\(5)         Tindi [(Magomedova 2012: 79)]{.c11}

[wac]{.c2 .c11}[ː]{.c2}[i                 k]{.c2 .c11}[j]{.c2 .c11
.c23}[\'e-ja                 rehã-ɬ]{.c2 .c11}[ː]{.c2}[i]{.c2
.c11}[ː]{.c2}[ ]{.c4 .c11}

[brother         two-num         year-nm.obl.erg]{.c4 .c11}

[muk\'u-w         ija         ]{.c2 .c11}[jac]{.c2 .c11 .c6}[ː]{.c2
.c6}[u]{.c2 .c11 .c6}[-č\'i]{.c2 .c11 .c6}

[little-m                 cop         ]{.c11}[sister-cont]{.c13 .c11
.c6}

['The brother is two years younger than the sister.' ]{.c11}

[]{.c4}

In most languages of Daghestan [elatives ]{.c6}[are used:]{.c4}

1.  [superelative in: ]{.c4}

<!-- -->

1.  [Standard Avar, Bagvalal and Karata (Avar-Andic);]{.c4}
2.  Standard Lezgian, Aghul, Archi^[\[1\]](#ftnt1){#ftnt_ref1}^[, Rutul
    and Tsakhur (Lezgic);  ]{.c4}
3.  [Itsari (Dargwa);]{.c4}
4.  [Hinuq, Tsez and Xvarshi (Tsezic);]{.c4}

<!-- -->

2.  [contelative in Botlikh, Godoberi and Chamalal (Avar-Andic);]{.c4}
3.  adelative in Kryz (Lezgic).

To these languages we might add those in which
[ablative]{.c6}[ ]{.c6}forms are used (6): Udi (Lezgic), Kumyk, Nogai
and Northern Azerbaijani (Turkic), and Armenian.[ Ablatives are commonly
employed to mark the standard of comparison in the languages of the
world (Creissels 2009: 624).]{.c4}

[]{.c4}

[(6)         North Azerbaijani (Širaliev & Sevortjan 1971: 47)]{.c4}

        [Bakı         ]{.c2}[Kirovabad-dan]{.c2
.c6}[         böyük-dür]{.c12 .c2}

[        ]{.c18}Baku         [Kirovabad-abl]{.c6}         big-cop.3sg

[        'Baku is bigger than Kirovabad.']{.c4}

[]{.c4}

[Essives ]{.c6}[are also quite frequent in Daghestan: ]{.c4}

1.  [superessive in Bezhta (Tsezic), Akusha (= Standard Dargwa), Mehweb
    and Kubachi (Dargwa);]{.c4}
2.  [contessive in Andi, Bagvalal (as an alternative to the
    superelative) and Tindi (Avar-Andic);]{.c4}
3.  [inessive in Bats (Nakh).]{.c4}

[]{.c4}

Northern Akhvakh (Avar-Andic) features the supertranslative case, while
in Hinuq (Tsezic) the so-called aloc-lative (i.e. animate location
lative) is used alongside the superelative (Forker 2019).

[]{.c4}

### 3[.2. Specialized comparative markers]{.c12 .c2} {#h.1ailga6cvzle .c0 .c14}

[]{.c4}

In some languages the standard of comparison is marked with a dedicated
suffix, sometimes called "[comparative suffix]{.c6}"
(7).^[\[b\]](#cmnt2){#cmnt_ref2}^[ This is true for: Chechen and Ingush
(Nakh), Hunzib (Tsezic), Archi, Budukh, Mukhad Rutul and Tabasaran
(Lezgic), Khinalug and Lak. ]{.c4}

[]{.c4}

[(7)         Chechen (Nichols 1994: 30)]{.c4}

        [iza         ]{.c2}[suo-l]{.c2 .c6}[                 dika
        v-u]{.c12 .c2}

        3sg         [1sg-cmpr]{.c6}[         good         m-cop]{.c4}

[        'He is better than me.']{.c4}

[]{.c4}

However, it should be pointed out that, in some cases, this comparative
suffix seems to include a spatial suffix, e.g. Khinalug
-[q'il:i]{.c2} (elative -[l:i]{.c2}), Northern Tabasaran
-[t'an]{.c2} and Southern Tabasaran -[č'an]{.c2} /
-[dakan]{.c2} (elative -[an]{.c2}), Budukh -[wor]{.c2} (elative
-[r]{.c2}).^[\[c\]](#cmnt3){#cmnt_ref3}^ Archi -[χur]{.c2}[ is reported
to have some residual spatial usages (Daniel & Ganenkov 2009:
673-674).]{.c4}

[]{.c4}

[+ link to the map and summary of the patterns displayed on it]{.c4 .c3}

[]{.c4 .c3}

[4]{.c3}[.]{.c3}[ The "localization" issue]{.c13 .c3 .c6} {#h.o6zojhao5hyp .c0 .c14}
---------------------------------------------------------

[]{.c4 .c3}

[A quite controversial question, which lies behind the classification of
spatially coded comparatives, concerns the semantics of localization
markers. In Section 3 we grouped languages according to whether they
feature a "super", "cont" or "ad" marker (along with the distinction
between elatives and
essives)]{.c3}[.]{.c3}^[\[d\]](#cmnt4){#cmnt_ref4}^[ However, to my
understanding, it is not straightforward what the semantic difference
between these three labels is. This is also demonstrated by the fact
that in the literature there is quite a great deal of contradictory
information concerning the labeling of such markers. Moreover, in some
cases, the decision to call a certain marker "super" or "cont" was taken
by the author based on the information provided in the Russian-language
literature, in which such labels are rarely employed (in most
Russian-language grammars the different localization markers are listed
by simply naming them "series 1", "series 2", and so on)]{.c3}[.]{.c3}

[]{.c4}

[References]{.c13 .c6} {#h.mdnma6dtvirh .c0 .c14}
----------------------

[]{.c4}

Bokarev, Evgenij A. 1949. [Sintaksis avarskogo jazyka]{.c2}[ \[Avar
Syntax\]. Moscow: AN SSSR.]{.c4}

Creissels, Denis. 2009. Spatial cases. In Andrej Malchukov & Andrew
Spencer (eds.), [The Oxford Handbook of Case]{.c2}[. Oxford/New York:
Oxford University Press. 609-625.]{.c4}

Daniel, Michael & Dmitry Ganenkov. 2009. Case marking in Daghestanian:
limits of elaboration. In Andrej Malchukov & Andrew Spencer (eds.), [The
Oxford Handbook of Case]{.c2}[. Oxford/New York: Oxford University
Press. 668-685.]{.c4}

Forker, Diana. 2019. The impact of language contact on Hinuq: Phonology,
morphology, syntax, and lexicon. [Language Typology and
Universals]{.c2}[ 71. 29-62.]{.c4}

Kibrik, Aleksandr E. 1977. [Opyt strukturnogo opisanija arčinskogo
jazyka. Tom II. Taksonomičeskaja grammatika]{.c2}[ \[Structural
description of Archi. Volume II. Taxonomic grammar. Moscow: Izdatel'stvo
Moskovskogo Universiteta.]{.c4}

Magomedova, Patimat T. 2012. [Tindinskij jazyk]{.c2}[ \[Tindi\].
Makhachkala: Institute of Language, Literature and Arts of Daghestan
Scientific Centre, Russian Academy of Sciences.]{.c4}

Mikailov, [K]{.c3}. Š. 1967. [Arčinskij jazyk]{.c2}[ \[Archi\].
Makhachkala: Institute of Language, Literature and Art of Daghestan
Scientific Centre, Russian Academy of Sciences.]{.c4}

Nichols, Johanna. 1994. Chechen. In Rieks Smeets (ed.), [The Indigenous
Languages of the Caucasus, Vol. 4: The Northeast Caucasian Languages,
Part 2]{.c2}[. Delmar, NY: Caravan Press. 1-77.]{.c4}

Saidova, Patimat A. 1973. [Godoberinskij jazyk. Grammatičeskij očerk,
teksty, slovar']{.c2}[ \[Godoberi. Grammar sketch, texts, dictionary\].
Makhachkala: Institute of History, Language and Literature of Daghestan
Scientific Centre, Russian Academy of Sciences.]{.c4}

Stassen, Leon. 2013. Comparative Constructions. In Matthew S. Dryer &
Martin Haspelmath (eds.), [The World Atlas of Language Structures
Online]{.c2}[. Leipzig: Max Planck Institute for Evolutionary
Anthropology. (Available online at http://wals.info/chapter/121,
Accessed on 2019-12-17.)]{.c4}

Širaliev, Mamedaga Š. & Èrvand V. Sevortjan. 1971. [Grammatika
azerbaijdžanskogo jazyka (fonetika, morfologija,
sintaksis)]{.c2}[ \[Azerbaijani grammar (phonetics, morphology,
syntax)\]. Baku: ÈLM.]{.c4}

<div>

[]{.c4}

</div>

------------------------------------------------------------------------

<div>

[\[1\]](#ftnt_ref1){#ftnt1}[ The superelative suffix
-]{.c27}[t:-iš]{.c27 .c2}[ is mentioned by Mikailov (1967: 60) as the
marker used to code the standard of comparison in Archi, but Kibrik
(1977: 59) reports the dedicated comparative marker -]{.c27}[χur]{.c2
.c27}[ instead.]{.c9}

</div>

::: {.c7}
[\[a\]](#cmnt_ref1){#cmnt1}[There will be a special chapter in the Atlas
devoted to this topic, so that in the other chapters involving spatial
forms we will simply refer to this chapter.]{.c4}
:::

::: {.c7}
[\[b\]](#cmnt_ref2){#cmnt2}[за этим теоретически может скрываться как а)
особая падежная форма компаратива, б) локативная форма, которая (почти)
сузилась до компаратива, в) вообще какая-то клитика \"чем\", которая
присоединется к абсолютиву; может быть имеет смысл различать такие
штуки]{.c4}
:::

::: {.c7}
[\[c\]](#cmnt_ref3){#cmnt3}[Мне кажется, что здесь не хватает фокуса вот
на этом движении от пространственного к компаративному употреблению. В
хиналугском это выглядит как компаративный показатель, который имеет
двучленную структуру. То есть очень похоже на то, что это
пространственная форма, которая специализировалась именно в этом
употреблении. В арчинском (у вас нет арчинского!)) есть показатель,
который называется компаративом, но который на самом деле имеет
некоторые остаточные пространственные функции. Это очень важный сюжет,
который я бы усилил - остаточность пространственных значений в
компаративных показателях.]{.c4}
:::

::: {.c7}
[\[d\]](#cmnt_ref4){#cmnt4}[мне кажется, композиционно в разделе про
локативное маркирование лучше сделать отдельный раздел про показатель
ориентации и отдельный - про показатель локализации, т.к. это два важных
и возможно независимых параметра; т.е.:]{.c4}

[- локативное]{.c4}

[\-- типология ориентаций]{.c4}

[\-- типология локализаций]{.c4}

[- нелокативное]{.c4}
:::
